### ISSUE TITLE
Publish weAudit to Open VSX

### ISSUE THREAD

**Issue by noraj** [trailofbits/vscode-weaudit#13]
Dear TrailOfBits extension author,
Please publish this weAudit extension to the Open VSX marketplace.

## Context

Unfortunately, as Microsoft prohibits usages of the Microsoft marketplace by any other products or redistribution of `.vsix` files from it, in order to use VS Code extensions in non-Microsoft products, we kindly ask that you take ownership of the VS Code extension namespace in [Open VSX](https://open-vsx.org/) and publish this extension on Open VSX.

## What is Open VSX? Why does it exist?

Open VSX is a vendor neutral alternative to the MS marketplace used by most other derivatives of VS Code like [VSCodium](https://vscodium.com/), [Gitpod](https://www.gitpod.io), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [Theia](https://theia-ide.org/)-based IDEs, and so on.

You can read on about Open VSX at the Eclipse Foundation's [Open VSX FAQ](https://www.eclipse.org/legal/open-vsx-registry-faq/).

## How can you publish to Open VSX?

The docs to publish an extension can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). This process is straightforward and shouldn't take too long. Essentially, you need an authentication token and to execute the `ovsx publish` command to publish your extension. There's also [a doc](https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md) explaining the whole process with an example GitHub Action workflow.

## Notes

I personally use code OSS, a FLOSS version of Virtual Studio Code built from the source, it's the [official ArchLinux package](https://archlinux.org/packages/extra/x86_64/code/). I wrote [an article](https://blog.raw.pm/en/FLOSS-version-of-vscode-and-extensions-gallery/) (a bit outdated) on the subject.

Here is another example of Github Action that works both for publishing your VS Code Extension to the [Open VSX Registry](https://open-vsx.org/) or the [Visual Studio Marketplace](https://marketplace.visualstudio.com/): https://github.com/HaaLeo/publish-vscode-extension.

**Comment by fcasal** [comment]
Hi @noraj,
thanks for the detailed request. We will look into this

**Comment by fcasal** [comment]
Hi @noraj, I just published v1.1.0 of weAudit to open-vsx https://open-vsx.org/extension/trailofbits/weaudit and it shows up on vscodium's marketplace.

Version 1.2.0 full of new features should be published by the end of the week.
