### ISSUE TITLE
Commands not found

### ISSUE THREAD

**Issue by gdraperi** [trailofbits/vscode-weaudit#14]
Hello,

I was trying to use the tool but I am facing some errors when I try to add notes and findings.

![weaudit](https://github.com/trailofbits/vscode-weaudit/assets/33750242/fed46674-dc25-48fd-b859-cc593cbffab0)

I installed the extension through the dedicated menu in Visual Studio Code.

How can I have more information to check if it comes from my install or from the extension?

Thanks,

**Comment by fcasal** [comment]
Hello @gdraperi,
could you give us a few more details on your installation method and workspace setup? 
- did you install weAudit directly from the marketplace, did you manually install the `weaudit.vsix` file, or another option?
- from your screenshot, it seems that the extension has not been activated yet. Do you have any file/folder/workspace open in vscode, or is it just an empty vscode window? If it is just an empty vscode window, try opening the folder you want to take notes on and try again.

**Comment by gdraperi** [comment]
Hello @fcasal 

Thanks for the feedback. Indeed, I reopened a project and everything works now.

Thanks!
