### ISSUE TITLE
Feature request: Option to unhighlight note/finding code block selection

### ISSUE THREAD

**Issue by ThreeHrSleep** [trailofbits/vscode-weaudit#18]
### Desired feature

Would appreciate having an option(toggle) to unhighlight highlighted note/finding selection(temporarily).

![Screenshot from 2024-03-26 10-53-07](https://github.com/trailofbits/vscode-weaudit/assets/151536303/f1be406f-6bb2-4de6-b8ea-9e102483d5ed)

### How is it useful ?
After going through a code-base multiple times,many auditors like doing a fresh pass(without seeing tags/comments that they've added during first few passes) to get new ideas & to get rid of any false assumptions that they might've made previously 

Option to turn off the highlighted selections can be helpful for us in that way

**Comment by fcasal** [comment]
Hello @ThreeHrSleep ,
you can already hide all your notes and findings (or other user's if you share the file with a teammate) by clicking on your username in the "WeAudit Files" tab

![hide_findings](https://github.com/trailofbits/vscode-weaudit/assets/17139618/5fcfd9a8-df10-4661-913f-be5e6d358fa9)

**Comment by ThreeHrSleep** [comment]
Ah! sorry ,my bad
Thanks for the response :)
closing the issue
