### ISSUE TITLE
Remove Cmd + K binding

### ISSUE THREAD

**Issue by piyush-saurabh** [trailofbits/vscode-weaudit#19]
weaudit extension is currently using `cmd + K` shortcut for adding notes - “weAudit: New Note from Selection”.

`cmd + K` is the default bindings in vscode for multiple operations like commenting a piece of code (`cmd+k c`), formatting (`cmd + k f`) etc. Adding this extension breaks the existing shortcuts. Requesting to change the default bindings to avoid breaking vscode's default shortcuts.

**Comment by fcasal** [comment]
Hi @piyush-saurabh,
thanks for letting us know. I will make sure that none of the default keybindings clash with vscode's keybinds
