### ISSUE TITLE
Feature request: Mark selection as reviewed

### ISSUE THREAD

**Issue by Kriskras99** [trailofbits/vscode-weaudit#20]
When auditing it can be nice to follow the code execution flow.
When doing this it is very useful to mark a function or a block of code as reviewed as opposed to the entire file.

**Comment by fcasal** [comment]
Hi @Kriskras99,
yes, this has been a feature we have planned for some time.

To work around this limitation, my workflow is: I create an extra note called "DONE", and if I need to partially mark a function as reviewed, I add the function region to that note with the "weAudit: Add Region to a Finding" command.

**Comment by Kriskras99** [comment]
> Hi @Kriskras99,
> yes, this has been a feature we have planned for some time.
> 
> To work around this limitation, my workflow is: I create an extra note called "DONE", and if I need to partially mark a function as reviewed, I add the function region to that note with the "weAudit: Add Region to a Finding" command.
> 
> 

That's a good workaround, thanks for the tip!

**Comment by fcasal** [comment]
Implemented in #21. Check out the readme for a gif of the new feature https://github.com/trailofbits/vscode-weaudit?tab=readme-ov-file#partially-audited-files
