### ISSUE TITLE
Feature request: Mark as pre-reviewed or multiple mark

### ISSUE THREAD

**Issue by n0kto** [trailofbits/vscode-weaudit#22]
A lot of auditors go through the code at least twice, it could be really useful to mark the code as "pre-reviewed" before "completly reviewed" or be able to put multiple mark on a file/region of a file.

**Comment by fcasal** [comment]
Hi @n0kto could you describe your intended workflow better?
Currently, you can add a note called "Pre-reviewed" with several regions, and then go through those one more time.

**Comment by n0kto** [comment]
Hi @fcasal,

The interesting behavior I wanted is the mark on the right of file. The idea came to my mind because I was currently auditing a protocol with a restricted scope (not all the protocol was included). 
The green mark on the right of the file was really helpful to see which file I needed to come back but I could not differenciate files I entirely checked twice.

Moreover I only use weAudit notes like a "to-do list": I put question I need to answer (as you said, like a "pre-reviewed") because there is just one type of note, so I cannot write explaination notes or other types of notes.

But even with several types of note or using "pre-reviewed" in my "to-do list", I should put one "pre-reviewed" note at least on every files in the scope (time-consuming). A double mark with one more "cmd + \+" would be more practical.

That’s just a proposal, maybe nobody uses weAudit notes like me, but in my process, have multiple "reviewed mark" could be a cool features instead of creating more notes. :)
