### ISSUE TITLE
Feature Request: Export findings in a file/markdown format for audit contests/reports.

### ISSUE THREAD

**Issue by n0kto** [trailofbits/vscode-weaudit#23]
A lot of auditors mainly does audit contests instead of private audits. It would be awesome to have a function to export our findings in a (markdown) file. At the moment I don’t see any reason for an auditor to fill in the finding details in the weAudit extension, since they has to rewrite/copy all on the audit contest plateform or a report file.

Feel free to tell me if I’m wrong and I didn’t catch the purpose of this tool!

**Comment by fcasal** [comment]
Hi @n0kto , thanks for the suggestion. 
Filling in the finding details serves to fill the Github issue markdown template that is generated when a github issue is created.

I agree that having the ability to export a subset of findings to markdown is useful. I'm closing this issue as there is a duplicate for this feature request https://github.com/trailofbits/vscode-weaudit/issues/16
