### ISSUE TITLE
Feature Request: Add a search bar for findings and notes

### ISSUE THREAD

**Issue by n0kto** [trailofbits/vscode-weaudit#28]
Hi,
It could be really useful to add a "find/search bar" for notes and findings.

- Concrete example:
If a write a note at the beginning of the audit, and want to update it with more information or delete it, I can not find this note quickly (especially when there is a ton of note once the entire code is audited).

**Comment by n0kto** [comment]
It only works when you have a blank space below the notes. Try to fill the box with notes and do `cmd + F`.

**Comment by fcasal** [comment]
This still works in that case if one of the items is selected, for example:
![search_bar_full](https://github.com/trailofbits/vscode-weaudit/assets/17139618/2513ade4-3adb-456a-8346-7bcc2d62ae25)

You can also call the `weAudit: Focus on List of Findings View` and then press cmd+f. 
I can make a weAudit command that opens this search bar by doing these two actions in succession.

**Comment by Vasco-jofra** [comment]
Can we also add a note on how to do this in the README? I wasn't aware that this was possible, and it's an awesome feature

**Comment by n0kto** [comment]
On VS Codium 1.82.2, it didn’t work, but on the latest version, all is working ! Thank you for your help!

**Comment by fcasal** [comment]
@Vasco-jofra , yes I have the gif ready for when I add the `weAudit: Search and Filter Findings` command
