### ISSUE TITLE
[Feature Request] Add "Mark Selection as Reviewed" instead of full File

### ISSUE THREAD

**Issue by nisedo** [trailofbits/vscode-weaudit#45]
Hi, I started using weAudit recently and it's great!

But for now, only the option of marking an entire file as reviewed is available: `weAudit: Mark File as Reviewed`.

I'd like to be able to select only a snippet of code (like an entire function) and mark it as reviewed to advance step by step in my audit, especially useful for large files / contracts.

And additionally, if all functions in a file have been marked as reviewed, the extension could detect this and mark the entire file as reviewed automatically.

**Comment by TheZ3ro** [comment]
I like this proposal!

**Comment by fcasal** [comment]
Hi @nisedo, I've just released a new weAudit version with this feature that works as @TheZ3ro mentioned
