### ISSUE TITLE
Support for opening GitLab issues

### ISSUE THREAD

**Issue by tmr232** [trailofbits/vscode-weaudit#6]
Can you add support for opening GitLab issues, if the repo URL points to Gitlab?

The URL query parameters need to be [named differently for Gitlab](https://docs.gitlab.com/ee/user/project/issues/create_issues.html#using-a-url-with-prefilled-values).

Thank you!

**Comment by fcasal** [comment]
Hello @tmr232, this should be easily doable.

To implement this, I imagine having a toggleable configuration github/gitlab on the extension settings, and then it would use the proper query parameters accordingly. Would that be in line with your use case?

**Comment by tmr232** [comment]
@fcasal Thanks for the quick reply!

Yes, a toggleable per-project configuration in the extension settings sounds like a great solution.

**Comment by Falcon9901** [comment]
Thanks for your helpful extension, Now while you're adding Gitlab support please make sure it will support self-hosted (on-premises) GitLab instances by accepting a Gitlab URL as a parameter in extension settings. This would enable the extension to work with both the cloud-hosted GitLab.com and self-hosted GitLab instances running on-premises.

**Comment by fcasal** [comment]
Hi @tmr232 @Falcon9901 ,
I've implemented this in #35. No configuration option is needed, as it works by checking whether the URL you are opening the issues for is on github.com.

Let me know if this solves this limitation for your use case!
