### ISSUE TITLE
Behavior of "Copy Audit Permalink" on findings with multiple regions

### ISSUE THREAD

**Issue by thomas-chauchefoin-bentley-systems** [trailofbits/vscode-weaudit#62]
Right now, using "Copy Audit Permalink" on a finding with multiple regions copies only a link to the first one. Whether users regroup all findings of given a bug class under the same entry or only the steps from sink to source, I feel like copying links to all regions would make reporting easier. For now I have a Python script for that, but I wouldn't mind having it in weAudit directly!

**Comment by fcasal** [comment]
Thanks for the suggestion!
Now, the button on the parent entry is "Copy All Audit Permalinks." The extension settings also have a new configuration to define the separator to join the links, which defaults to "\n".

**Comment by thomas-chauchefoin-bentley-systems** [comment]
Perfect, thank you! :)
